#!/usr/bin/env python3
"""Normalize cached SRA-query CSVs to the current 6-column schema.

Background
----------
`rnaseq_reads/sra_query/<species>.sra_query.csv` files were written by several
generations of the SRA_QUERY / SRA_QUERY_BATCH processes in nextflow/funannotate.nf:

  4-column (oldest):  species_tag,taxonid,sra_accession,spots
  5-column:           species_tag,taxonid,sra_accession,spots,platform
  6-column (current): species_tag,taxonid,sra_accession,spots,platform,layout

The consuming SRA_FETCH_SE process routes an accession to single-end handling only
when its `layout` column == SINGLE; a missing column reads as empty and defaults to
PAIRED, so pre-6-column files can never route to SE fetch. This script upgrades the
older files to the 6-column schema in place so the schema is uniform and the
layout-based routing can read them.

Correctness of the stamped layout
---------------------------------
Every pre-6-column query was generated by an esearch filtered on `PAIRED[Layout]`
(verified in git history at commit f7db039~1), so every *data row* in a 4- or
5-column file is PAIRED by construction. We therefore stamp `PAIRED` as the layout.
4-column files additionally lack `platform`; on disk they are all header-only (no
data rows), so no platform value has to be invented — but if a data row is ever
encountered it is reported and skipped rather than guessed.

What this does NOT do
---------------------
This is a pure schema/format normalization. It does not touch the network and cannot
discover new single-end data for species whose old PAIRED-only query returned nothing
(header-only files). Finding SE data for those requires deleting the stale header-only
CSVs and re-running the pipeline so SRA_QUERY re-queries with the SINGLE fallback.

Usage
-----
    # dry-run (default): report what would change, touch nothing
    python3 scripts/one-off/refresh_sra_query_layout.py

    # apply: rewrite files atomically in place
    python3 scripts/one-off/refresh_sra_query_layout.py --apply

    # restrict to a directory or limit count while testing
    python3 scripts/one-off/refresh_sra_query_layout.py --dir rnaseq_reads/sra_query --limit 20
"""
from __future__ import annotations

import argparse
import glob
import os
import sys
import tempfile

HEADER_6 = "species_tag,taxonid,sra_accession,spots,platform,layout"


def convert(lines: list[str]) -> tuple[list[str] | None, str]:
    """Return (new_lines, reason).

    new_lines is None when no change is needed or the file cannot be safely
    converted; reason is a short classification string for reporting.
    """
    if not lines:
        return None, "empty-file"

    header_cols = lines[0].count(",") + 1
    if header_cols == 6:
        return None, "already-6col"
    if header_cols not in (4, 5):
        return None, f"unexpected-{header_cols}col-header"

    out = [HEADER_6]
    for row in lines[1:]:
        if not row.strip():
            continue
        n = row.count(",") + 1
        if n == 5:
            out.append(row + ",PAIRED")
        elif n == 4:
            # 4-col data row lacks platform; we will not invent one.
            return None, "4col-data-row-unhandled"
        elif n == 6:
            out.append(row)  # already fine, leave as-is
        else:
            return None, f"unexpected-{n}col-data-row"
    return out, f"{header_cols}col->6col"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", default="rnaseq_reads/sra_query",
                    help="directory of *.sra_query.csv files (default: %(default)s)")
    ap.add_argument("--apply", action="store_true",
                    help="rewrite files in place (default: dry-run, no changes)")
    ap.add_argument("--limit", type=int, default=0,
                    help="process at most N files (0 = all; for testing)")
    args = ap.parse_args()

    files = sorted(glob.glob(os.path.join(args.dir, "*.sra_query.csv")))
    if not files:
        print(f"[ERROR] no *.sra_query.csv files found under {args.dir}", file=sys.stderr)
        return 1
    if args.limit:
        files = files[: args.limit]

    counts: dict[str, int] = {}
    converted = 0
    skipped_unsafe = []
    for path in files:
        with open(path) as fh:
            lines = fh.read().splitlines()
        new_lines, reason = convert(lines)
        counts[reason] = counts.get(reason, 0) + 1
        if new_lines is None:
            if reason.endswith("unhandled") or reason.startswith("unexpected"):
                skipped_unsafe.append((path, reason))
            continue
        converted += 1
        if args.apply:
            d = os.path.dirname(path)
            fd, tmp = tempfile.mkstemp(dir=d, prefix=".tmp_sraq_")
            with os.fdopen(fd, "w") as out:
                out.write("\n".join(new_lines) + "\n")
            os.replace(tmp, path)  # atomic within same filesystem

    mode = "APPLIED" if args.apply else "DRY-RUN (no files changed)"
    print(f"=== refresh_sra_query_layout [{mode}] ===")
    print(f"scanned:   {len(files)} files under {args.dir}")
    print(f"converted: {converted} file(s) to 6-column")
    print("breakdown by classification:")
    for reason in sorted(counts):
        print(f"   {reason:28s} {counts[reason]}")
    if skipped_unsafe:
        print(f"\n[WARN] {len(skipped_unsafe)} file(s) skipped as unsafe to auto-convert:")
        for path, reason in skipped_unsafe[:20]:
            print(f"   {reason:28s} {os.path.basename(path)}")
        if len(skipped_unsafe) > 20:
            print(f"   ... and {len(skipped_unsafe) - 20} more")
    if not args.apply and converted:
        print("\nRe-run with --apply to write these changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
