//
// Helper functions shared across the funannotate pipeline.
//
// funannotate-specific (they read params.target, launchDir/rnaseq_reads, the
// shared ab-initio parameter store), so they live here rather than in
// modules/common/utils.nf, which is cross-pipeline.
//
// Plain functions, not a lib/ class -- see REFACTOR_NEXTFLOW_PLAN.md section 2.1.
//

// A funannotate step's GenBank output may be stored uncompressed (.gbk) or
// gzip-compressed (.gbk.gz) so completed folders can be compressed to save space.
// Returns the existing non-empty file (preferring .gbk), or null if neither exists.
// Use this for completion/skip gating so a compressed result still counts as "done".
def gbkResult(String dir, String out) {
    def plain = file("${dir}/${out}.gbk")
    if (plain.exists() && plain.size() > 0) return plain
    def gz = file("${dir}/${out}.gbk.gz")
    if (gz.exists() && gz.size() > 0) return gz
    return null
}

// Clean/masked genomes in input_clean_genomes may be stored gzip-compressed (.gz) to
// save space. Given the uncompressed base path (e.g. .../<asmid>.fa or .../<asmid>.masked.fasta),
// returns the existing non-empty file, preferring the compressed form. Falls back to the
// plain path object when neither exists, so callers' .exists() checks still report missing.
def genomeFile(String base) {
    def gz = file("${base}.gz")
    if (gz.exists() && gz.size() > 0) return gz
    return file(base)
}

def staleRnaseq(String out, String species) {
    def species_tag = species.replaceAll(/\s+/, '_')
    def gbk = gbkResult("${params.target}/${out}/predict_results", out)
    if (gbk == null) return false  // predict hasn't run yet; normal path handles it
    def r1      = file("${launchDir}/rnaseq_reads/${species_tag}_norm_R1.fastq.gz")
    def se      = file("${launchDir}/rnaseq_reads/${species_tag}_norm_SE.fastq.gz")
    def trinity = file("${launchDir}/rnaseq_data/${species_tag}.trinity-GG.fasta")
    def r1_newer      = r1.exists()      && r1.size() > 0      && r1.lastModified()      > gbk.lastModified()
    def se_newer      = se.exists()      && se.size() > 0      && se.lastModified()      > gbk.lastModified()
    def trinity_newer = trinity.exists() && trinity.size() > 0 && trinity.lastModified() > gbk.lastModified()
    if (r1_newer || se_newer || trinity_newer) {
        log.info "stale prediction for ${out}: rnaseq/trinity newer than GBK — scheduling retrain+repredict"
        return true
    }
    return false
}

// ── Species-level ab-initio parameter reuse (todo/species_level_abinitio_reuse.md) ──
// Backfilled/refreshed out-of-band by nextflow/bin/species_reuse_clusters.py, which
// writes both abinitio_reuse_csv and the per-species
// params.gene_prediction_shared_abinitio/<species_tag>/parameters.json stores this
// reads. Not generated by this workflow. Lives as a top-level sibling of
// params.target (not nested inside it) since it's shared across every project tree
// that annotates the same species, not scoped to one genome_annotation/ run.

// Absolute path to a species' shared ab-initio parameters.json, or null if the
// species has no backfilled store yet (species_reuse_clusters.py hasn't run for it,
// or its representative's own PREDICT never completed -- see plan S4.3 "representative
// failure/skip fallback": no store on disk is the correct, safe signal to fall back
// to independent training, not an error).
def sharedParamsJsonFor(String species) {
    def species_tag = species.replaceAll(/\s+/, '_')
    def json = file("${params.gene_prediction_shared_abinitio}/${species_tag}/parameters.json")
    return (json.exists() && json.size() > 0) ? json : null
}

// A reuse_eligible strain's GBK must be considered stale if the shared parameters.json
// it was predicted with has since been refreshed (representative re-annotated, or the
// ANI/reuse assignment changed) -- mirrors staleRnaseq's shape/purpose.
def staleSharedParams(String out, def sharedJson) {
    if (sharedJson == null) return false
    def gbk = gbkResult("${params.target}/${out}/predict_results", out)
    if (gbk == null) return false  // predict hasn't run yet; normal path handles it
    if (sharedJson.lastModified() > gbk.lastModified()) {
        log.info "stale prediction for ${out}: shared ab-initio parameters newer than GBK — scheduling repredict"
        return true
    }
    return false
}

// Eagerly loads abinitio_reuse_csv into out -> [species, reuse_eligible] (mirrors the
// suppressSet pattern below: a small side-table read once at parse time, not through
// the dataflow model). Returns an empty map if the feature is off or the CSV doesn't
// exist yet (e.g. species_reuse_clusters.py hasn't been run for this dataset) --
// every row then falls through to today's independent-training behavior unchanged.
def loadAbinitioReuseMap() {
    def m = [:]
    if (!params.share_abinitio_params.toBoolean()) return m
    def csv = file(params.abinitio_reuse_csv as String)
    if (!csv.exists()) {
        log.warn "share_abinitio_params=true but abinitio_reuse_csv not found: ${csv} — all strains train independently"
        return m
    }
    def lines = csv.readLines()
    if (lines.size() < 2) return m
    def header = lines[0].split(',', -1)*.trim()
    def iSpecies  = header.indexOf('species')
    def iOut      = header.indexOf('out')
    def iEligible = header.indexOf('reuse_eligible')
    lines.drop(1).each { line ->
        def f = line.split(',', -1)
        if (f.size() <= [iSpecies, iOut, iEligible].max()) return
        m[f[iOut].trim()] = [
            species       : f[iSpecies].trim(),
            reuse_eligible: f[iEligible].trim().toLowerCase() == 'true',
        ]
    }
    log.info "Loaded ${m.size()} ab-initio reuse assignments from ${csv} (${m.count { it.value.reuse_eligible }} reuse_eligible)"
    return m
}
