CREATE TABLE aa_frequency(species_prefix VARCHAR, amino_acid VARCHAR, frequency DOUBLE);
CREATE TABLE asm_stats(LOCUSTAG VARCHAR, SPECIES VARCHAR, FILENAME VARCHAR, CONTIG_COUNT BIGINT, TOTAL_LENGTH BIGINT, MIN BIGINT, MAX BIGINT, MEDIAN BIGINT, MEAN DOUBLE, L50 BIGINT, N50 BIGINT, L90 BIGINT, N90 BIGINT, GC_PERCENT DOUBLE, T2T_SCAFFOLDS BIGINT, TELOMERE_FWD BIGINT, TELOMERE_REV BIGINT);
CREATE TABLE cazy(species_prefix VARCHAR, HMM_id VARCHAR, profile_length BIGINT, protein_id VARCHAR, protein_length BIGINT, evalue DOUBLE, q_start BIGINT, q_end BIGINT, s_start BIGINT, s_end BIGINT, coverage DOUBLE);
CREATE TABLE cazy_overview(species_prefix VARCHAR, protein_id VARCHAR, EC VARCHAR, cazyme_fam VARCHAR, sub_fam VARCHAR, diamond_fam VARCHAR, substrate VARCHAR, toolcount BIGINT);
CREATE TABLE chrom_info(LOCUSTAG VARCHAR, chrom_name VARCHAR, length BIGINT, GC_percent DOUBLE, GC_count BIGINT, left_50 VARCHAR, right_50 VARCHAR, lower_masked BIGINT, N_masked BIGINT);
CREATE TABLE codon_frequency(species_prefix VARCHAR, codon VARCHAR, frequency DOUBLE);
CREATE TABLE funguild(species_prefix VARCHAR, species VARCHAR, growthForm VARCHAR, guild VARCHAR, trophicMode VARCHAR, confidenceRanking VARCHAR);
CREATE TABLE gene_exons(exon_id VARCHAR, transcript_id VARCHAR, "order" BIGINT, chrom VARCHAR, "start" BIGINT, "end" BIGINT, strand BIGINT, GC_content DOUBLE, locustag VARCHAR);
CREATE TABLE gene_info(gene_id VARCHAR, LOCUSTAG VARCHAR, chrom VARCHAR, "start" BIGINT, "end" BIGINT, strand BIGINT, gene_type VARCHAR, locustag_1 VARCHAR);
CREATE TABLE gene_introns(intron_id VARCHAR, transcript_id VARCHAR, intron_number BIGINT, chrom VARCHAR, "start" BIGINT, "end" BIGINT, strand BIGINT, splice_5 VARCHAR, splice_3 VARCHAR, GC_content DOUBLE, codon_position BIGINT, codon_frame BIGINT, seq VARCHAR, locustag VARCHAR);
CREATE TABLE gene_pairwise_distances(species_prefix VARCHAR, left_gene VARCHAR, right_gene VARCHAR, distance BIGINT);
CREATE TABLE gene_proteins(gene_id VARCHAR, protein_id VARCHAR, transcript_id VARCHAR, length BIGINT, peptide VARCHAR, md5checksum VARCHAR, locustag VARCHAR);
CREATE TABLE gene_transcripts(gene_id VARCHAR, transcript_id VARCHAR, chrom VARCHAR, "start" BIGINT, "end" BIGINT, strand BIGINT, is_partial BOOLEAN, has_start_codon VARCHAR, has_stop_codon VARCHAR, CDS_sequence VARCHAR, CDS_length BIGINT, md5checksum VARCHAR, locustag VARCHAR);
CREATE TABLE gene_trna(gene_id VARCHAR, amino_acid VARCHAR, codon VARCHAR, locustag VARCHAR);
CREATE TABLE idp(species_prefix VARCHAR, protein_id VARCHAR, IDP_start BIGINT, IDP_end BIGINT, IDP_length BIGINT, mean_score DOUBLE);
CREATE TABLE idp_summary(species_prefix VARCHAR, protein_id VARCHAR, IDP_residues BIGINT, IDP_fraction DOUBLE, length BIGINT);
CREATE INDEX idx_aa_locustag ON aa_frequency(species_prefix);
CREATE INDEX idx_cazy_HMM ON cazy(HMM_id);
CREATE INDEX idx_cazy_locustag ON cazy(species_prefix);
CREATE INDEX idx_cazy_overview_locustag ON cazy_overview(species_prefix);
CREATE INDEX idx_cazy_overview_protein_id ON cazy_overview(protein_id);
CREATE INDEX idx_cazy_protein_id ON cazy(protein_id);
CREATE INDEX idx_chrominfo_locustag ON chrom_info(LOCUSTAG);
CREATE UNIQUE INDEX idx_chrominfo_locustag_chrom ON chrom_info(LOCUSTAG, chrom_name);
CREATE INDEX idx_codonfreq_locustag ON codon_frequency(species_prefix);
CREATE INDEX idx_funguild_locustag ON funguild(species_prefix);
CREATE INDEX idx_gene_exon_locustag ON gene_exons(locustag);
CREATE INDEX idx_gene_exons_transcript_id ON gene_exons(transcript_id);
CREATE INDEX idx_gene_id ON gene_proteins(gene_id);
CREATE UNIQUE INDEX idx_gene_info_gene_id ON gene_info(gene_id);
CREATE INDEX idx_gene_info_locustag ON gene_info(locustag);
CREATE INDEX idx_gene_introns ON gene_introns(locustag);
CREATE INDEX idx_gene_introns_chrom ON gene_introns(chrom);
CREATE UNIQUE INDEX idx_gene_introns_intronid ON gene_introns(intron_id);
CREATE INDEX idx_gene_introns_txid ON gene_introns(transcript_id);
CREATE INDEX idx_gene_proteins_gene_id ON gene_proteins(gene_id);
CREATE INDEX idx_gene_proteins_locustag ON gene_proteins(locustag);
CREATE UNIQUE INDEX idx_gene_proteins_protein_id ON gene_proteins(protein_id);
CREATE INDEX idx_gene_proteins_tx_id ON gene_proteins(transcript_id);
CREATE UNIQUE INDEX idx_gene_pw_genes ON gene_pairwise_distances(left_gene, right_gene);
CREATE INDEX idx_gene_pw_locustag ON gene_pairwise_distances(species_prefix);
CREATE UNIQUE INDEX idx_gene_trna_gene_id ON gene_trna(gene_id);
CREATE INDEX idx_gene_trna_locustag ON gene_trna(locustag);
CREATE INDEX idx_gene_tx_chrom ON gene_transcripts(chrom);
CREATE UNIQUE INDEX idx_gene_tx_transcript_id ON gene_transcripts(transcript_id);
CREATE INDEX idx_gene_tx_transcripts_gene_id ON gene_transcripts(gene_id);
CREATE INDEX idx_gene_tx_transcripts_locustag ON gene_transcripts(locustag);
CREATE INDEX idx_idp_prefix ON idp_summary(species_prefix);
CREATE INDEX idx_idp_protein ON idp(protein_id, IDP_start);
CREATE INDEX idx_idpsum_prefix ON idp_summary(species_prefix);
CREATE INDEX idx_idpsum_protein ON idp_summary(protein_id);
CREATE INDEX idx_merops_locustag ON merops(species_prefix);
CREATE INDEX idx_merops_protein_id ON merops(protein_id);
CREATE INDEX idx_og ON mmseqs_orthogroup_clusters(orthogroup);
CREATE UNIQUE INDEX idx_og_count ON mmseqs_orthogroup_cluster_count(orthogroup);
CREATE INDEX idx_pfamUoT_locustag ON pfam(species_prefix);
CREATE INDEX idx_pfamUoT_pfam_id ON pfam(pfam_id);
CREATE INDEX idx_pfamUoT_protein_id ON pfam(protein_id);
CREATE INDEX idx_pfam_locustag ON pfam(species_prefix);
CREATE INDEX idx_pfam_pfam_id ON pfam(pfam_id);
CREATE INDEX idx_pfam_protein_id ON pfam(protein_id);
CREATE INDEX idx_prosite_locus ON prosite(species_prefix);
CREATE INDEX idx_prosite_protein_ud ON prosite(protein_id);
CREATE INDEX idx_signalp_locustag ON signalp(species_prefix);
CREATE INDEX idx_signalp_protein_id ON signalp(protein_id);
CREATE UNIQUE INDEX idx_species_asm ON species(ASMID);
CREATE UNIQUE INDEX idx_species_locustag ON species(LOCUSTAG);
CREATE INDEX idx_species_species ON species(SPECIES, GENUS);
CREATE INDEX idx_species_speciesin ON species(SPECIESIN);
CREATE UNIQUE INDEX idx_stats_locustag ON asm_stats(LOCUSTAG);
CREATE INDEX idx_targetp_proteinid ON targetp(protein_id);
CREATE INDEX idx_targetp_species ON targetp(species_prefix);
CREATE INDEX idx_tid ON mmseqs_orthogroup_clusters(transcript_id);
CREATE INDEX idx_tmhmm_locus ON tmhmm(species_prefix);
CREATE INDEX idx_tmhmm_protein_id ON tmhmm(protein_id);
CREATE TABLE merops(species_prefix VARCHAR, protein_id VARCHAR, merops_id VARCHAR, percent_identity DOUBLE, aln_length BIGINT, mismatches BIGINT, gap_openings BIGINT, q_start BIGINT, q_end BIGINT, s_start BIGINT, s_end BIGINT, evalue DOUBLE, bitscore DOUBLE);
CREATE TABLE mmseqs_orthogroup_cluster_count(orthogroup VARCHAR PRIMARY KEY, group_count BIGINT);
CREATE TABLE mmseqs_orthogroup_clusters(orthogroup VARCHAR, transcript_id VARCHAR);
CREATE TABLE pfam(protein_id VARCHAR, pfam_id VARCHAR, pfam_acc VARCHAR, pfam_len BIGINT, full_seq_e_value DOUBLE, full_seq_score DOUBLE, full_seq_bias DOUBLE, domain_num BIGINT, domain_num_of BIGINT, domain_c_evalue DOUBLE, domain_i_evalue DOUBLE, domain_score DOUBLE, domain_bias DOUBLE, hmm_from BIGINT, hmm_to BIGINT, ali_from BIGINT, ali_to BIGINT, env_from BIGINT, env_to BIGINT, species_prefix VARCHAR);
CREATE TABLE pfam_UoT(protein_id VARCHAR, pfam_id VARCHAR, full_seq_e_value DOUBLE, full_seq_score DOUBLE, full_seq_bias DOUBLE, domain_num BIGINT, domain_num_of BIGINT, domain_c_evalue DOUBLE, domain_i_evalue DOUBLE, domain_score DOUBLE, domain_bias DOUBLE, hmm_from BIGINT, hmm_to BIGINT, ali_from BIGINT, ali_to BIGINT, env_from BIGINT, env_to BIGINT, species_prefix VARCHAR);
CREATE TABLE prosite(species_prefix VARCHAR, protein_id VARCHAR, "start" BIGINT, "end" BIGINT, pattern VARCHAR);
CREATE TABLE signalp(species_prefix VARCHAR, protein_id VARCHAR, peptide_start BIGINT, peptide_end BIGINT, probability DOUBLE);
CREATE TABLE species(ASMID VARCHAR, SPECIESIN VARCHAR, STRAIN VARCHAR, BIOPROJECT VARCHAR, NCBI_TAXONID BIGINT, BUSCO_LINEAGE VARCHAR, PHYLUM VARCHAR, SUBPHYLUM VARCHAR, "CLASS" VARCHAR, SUBCLASS VARCHAR, "ORDER" VARCHAR, "FAMILY" VARCHAR, GENUS VARCHAR, SPECIES VARCHAR, LOCUSTAG VARCHAR);
CREATE TABLE targetp(species_prefix VARCHAR, protein_id VARCHAR, prediction VARCHAR, probability DOUBLE, cleavage_position_start BIGINT, cleavage_position_end BIGINT, cleavage_probability DOUBLE, motif VARCHAR);
CREATE TABLE tmhmm(species_prefix VARCHAR, protein_id VARCHAR, len BIGINT, ExpAA DOUBLE, First60 DOUBLE, PredHel BIGINT, Topology VARCHAR);
